debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedByDefault = false

# uncomment and modify for letsenrypt
#[acme]
#email = "your-email-here@my-awesome-app.org"
#storage = "acme.json"
#entryPoint = "https"
#onHostRule = true
#onDemand = true
#[acme.httpChallenge]
#entryPoint = "http"
